############################################################################################
#
# Docker-compose configuration file for sharelatex with multi-byte language
# 04/23/2017 Kazuma Okuda
#
############################################################################################

version: '2'
services:

    #
    # 1) Sharelatex container
    #

    sharelatex:

        restart: always

        build: ./

        container_name: sharelatex

        depends_on:
            - sharemongo
            - shareredis

        privileged: true

        dns:
            # Specify Google Public DNS for resolving smtp-server name
            - "8.8.8.8"        

        ports:
            # For HTTP serveice
            - "80:80"
            # For Email service (i.e. sending invitation mail)
            - "25:25"
            - "587:587"
            - "465:465"

        links:
            - sharemongo
            - shareredis

        volumes:
            - /data/sharelatex:/var/lib/sharelatex

        environment:           

            # Site configurations
            SHARELATEX_APP_NAME: "ShareLaTeX (Power electronics Laboratory Edition)"
            SHARELATEX_NAV_TITLE: "ShareLaTeX - University of Tsukuba Power electronics Laboratory Edition"
            SHARELATEX_SITE_URL: http://localhost
            SHARELATEX_PASSWORD_VALIDATION_MIN_LENGTH: 8
            SHARELATEX_PASSWORD_VALIDATION_MAX_LENGTH: 64
            SHARELATEX_PASSWORD_VALIDATION_PATTERN: "abc123"

            # Specify email address (usually of administrator)
            # Same addresses among followings are recommended 
            SHARELATEX_ADMIN_EMAIL: "okuda.kazuma.wp@alumni.tsukuba.ac.jp"
            SHARELATEX_EMAIL_FROM_ADDRESS: "okuda.kazuma.wp@alumni.tsukuba.ac.jp"
            SHARELATEX_EMAIL_REPLY_TO: "okuda.kazuma.wp@alumni.tsukuba.ac.jp"

            # Specify external smtp server authentification
            SHARELATEX_EMAIL_SMTP_HOST: smtp.gmail.com
            SHARELATEX_EMAIL_SMTP_PORT: 465
            SHARELATEX_EMAIL_SMTP_USER: okuda.kazuma.wp
            SHARELATEX_EMAIL_SMTP_PASS: s1520333
           
            # Additional configurations for smtp-server connection
            SHARELATEX_EMAIL_SMTP_SECURE: 'true'
            SHARELATEX_EMAIL_SMTP_TLS_REJECT_UNAUTH: 'true'
            SHARELATEX_EMAIL_SMTP_IGNORE_TLS: 'false'
           
            # Internal settings 
            SHARELATEX_MONGO_URL: mongodb://sharemongo/sharelatex
            SHARELATEX_REDIS_HOST: shareredis

#            # Additional configurations
#            SHARELATEX_CUSTOM_EMAIL_FOOTER: "<div>This system is run by department x </div>"
#            SHARELATEX_HEADER_IMAGE_URL: http://somewhere.com/mylogo.png
#            SHARELATEX_LEFT_FOOTER: '[{"text": "Powered by <a href=\"https://www.sharelatex.com\">ShareLaTeX</a> 2016"},{"text": "Another page I want to link to can be found <a href=\"here\">here</a>"} ]'
#            SHARELATEX_RIGHT_FOOTER: '[{"text": "Hello I am on the Right"} ]'
#            #Set for SSL via nginx-proxy
#            VIRTUAL_HOST: 103.112.212.22          

    #
    # 2) MongoDB container
    #
    
    sharemongo:
        restart: always
        image: mongo
        container_name: sharemongo
        expose:
            - 27017
        volumes:
            - /data/mongo:/data/db
    
    #
    # 3) Redis-server container
    #
    
    shareredis:
        restart: always
        image: redis
        container_name: shareredis
        expose:
            - 6379
        volumes:
            - /data/redis:/data
            
